{% set name = "pytrackmate" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39992816c43db900d37371cd8cac0801fecda7bbf9c0c1e524c5ce357d6512ac

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vvv  --no-deps"
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip

  run:
    - python >={{ python_min }}
    - pandas
    - numpy

test:
  commands:
    - nosetests
  imports:
    - pytrackmate
  requires:
    - nose
    - python {{ python_min }}

about:
  home: https://github.com/hadim/pytrackmate/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Import Trackmate XML files in Python as Pandas dataframe.'
  license_family: BSD

extra:
  recipe-maintainers:
    - hadim
