context:
  name: pytrackmate
  version: "1.3.4"
  python_min: "3.10"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: b9376cd39fc9e74df0f727dfb19146b757354ef780795dd8a5c5b6d47a489f3c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vvv  --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python >=${{ python_min }}
    - pandas
    - numpy

tests:
  - python:
      imports:
        - pytrackmate
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Import Trackmate XML files in Python as Pandas dataframe.
  homepage: https://github.com/hadim/pytrackmate/

extra:
  recipe-maintainers:
    - hadim
