context:
  name: pytrackmate
  version: "1.3.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: cda22143c9649fd43cd8b9cd11c3d36ae6b33b5e6f8decfa359003789a1bbbb7

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vvv  --no-deps

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - pandas
    - numpy

tests:
  - python:
      imports:
        - pytrackmate
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - nose
        - python ${{ python_min }}.*
    script:
      - nosetests

about:
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Import Trackmate XML files in Python as Pandas dataframe.
  homepage: https://github.com/hadim/pytrackmate/

extra:
  recipe-maintainers:
    - hadim
