travis:
  secure:
    BINSTAR_TOKEN: pBPwOAeunRCEGnhPP8kufiCyOQQCa5gsWb7+EJu69o9VNA6puerPsNlw10S7IAjPGhntZ/8bGtvGtbbAC6l7HGb6ZFXV+wzo2scpZr1elZ/29CTfOF5BanrreIOvz4fL3Bg6q/wuSqIl4f6O0lLq2NJoai/SVyO9CGqNIVMatXiedwz1NtqYiyoQobBfCMqgoQnSWfQjrr8ZRr/B2nTbD2kVUcYjYN1/6wP0FlKCFKAY28rsIb0ktL1sJLewD2uaxM7eRy21SATTGJA8LMS2L+oGgOUbVtR6seZAaVzetk11d6betSC9IHB1uMmfjCEPFYbvEHk4dVivUFHy64InL8BMcHOQpw+OeplOGV//S7nNwjIUrmjm5O6jzh2R7+Tb4wJG8XtifmSU6T1/m68dzLXBkLlxe/eSao1K4zeMo6H0q/WSV0Xf2FgTBA9uQPa/WjkTYzp/lfyikb1tfIVyVWiutVgBxWcjy/blSyyVreCOhq6Bjq/ZV0TOdEJoqI5l1aJHMIk9Nl8YKT9KCi9gaRCKSJZpgu1CfzFG39eXEMXeESCdEXW41mTUozZAP+CGtfOaJMKUQKWpjgeJ1Etw56X2sp9dMd7G3Pz1Su99wIXoYpLIOx0M+vMzrtW9tL6iWRR1M0gN54DF8VfSJ8TzSBADrQOz1mKKBeKpRiV1U7k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
