travis:
  secure:
    BINSTAR_TOKEN: O35gG2gSBFtI9wS4Wy7xdXGuJAVBHp//7A8JwwEUaeXmDP6k0C2rEKjBlRanza9bCbOhKTTm7WaYn92g/J7UuRwUFgZwaOVPrPJbdHjYkS09M3bZ/6p76cnZxkKH0bHT0f///bsNtqs82simnfXbDIOU+hU8VUsUBec9RFvWJEveJEdoLnJwRC9s8p2vv0UWWYYEpk92M6vJ0oxDH/daktTH73wPomV2eO44VwS87WkzM6b45QQR3Z1pbrznOEVG4apUO9X3sV5aZxSEnHph+A3CJ1LN6NpfPy+8aRranSfj+SKJ/whRKZsK0gGr8VVJ3dm9ewGe5GZ4q1k3BUkVxThEbF18M3QCjReRzaxj7y4YMweVtkxORCIkcY021bnVQ+h/uKQ8AvB3WofgJjvr+t6/b+s3oX0tbZ8Y3JFJQZAOecKmQ3vjWEE30ZB9a7Y00gXgZVpgJeeqtf5t8sBM+N8sCe5GYnZIb5xCUH5M8JcnREAhTOVvz2vHa41aJzysMA7WHPlrMkdYYVBdltM/e5KGyTF3TpHR3lGufvQNAIP72UbYZVJHc7oWqUbi95xoup5fq48Fz8T27R1f4ThqbngLjm2aKX/1KmfIQxOd+AQoP+WoLMeRFlPtO6LyF21jrmgtsnm1rxXY+BK5ri6uW4hTa4aRfs1pMuxZYveOXh8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
